import streamlit as st
import pandas as pd
import joblib

st.set_page_config(
    page_title="Credit Card Fraud Detection",
    page_icon="💳",
    layout="wide"
)

@st.cache_resource
def load_model():
    return joblib.load("credit_card_fraud_model.joblib")

model = load_model()

st.title("💳 Credit Card Fraud Detection System")

st.write(
    "Machine Learning based system for detecting whether "
    "a credit card transaction is legitimate or potentially fraudulent."
)

st.divider()

st.sidebar.header("Project Information")
st.sidebar.write("""
**Model:** Logistic Regression

**Dataset:** Credit Card Fraud Detection

**Features:** 30

**Target:**
- 0 = Legitimate
- 1 = Fraud
""")

st.sidebar.info(
    "This system is developed for educational and demonstration purposes."
)

st.header("Enter Transaction Details")

time_value = st.number_input(
    "Time",
    min_value=0.0,
    value=0.0,
    step=1.0
)

amount_value = st.number_input(
    "Transaction Amount",
    min_value=0.0,
    value=100.0,
    step=1.0
)

st.subheader("Transaction Features V1 - V14")

v_values = {}

cols = st.columns(4)

for i in range(1, 15):
    with cols[(i - 1) % 4]:
        v_values[f"V{i}"] = st.number_input(
            f"V{i}",
            value=0.0,
            format="%.6f"
        )

st.subheader("Transaction Features V15 - V28")

cols = st.columns(4)

for i in range(15, 29):
    with cols[(i - 15) % 4]:
        v_values[f"V{i}"] = st.number_input(
            f"V{i}",
            value=0.0,
            format="%.6f"
        )

if st.button(
    "🔍 Check Transaction",
    type="primary",
    use_container_width=True
):

    input_data = {
        "Time": time_value
    }

    input_data.update(v_values)
    input_data["Amount"] = amount_value

    input_df = pd.DataFrame([input_data])

    feature_order = (
        ["Time"] +
        [f"V{i}" for i in range(1, 29)] +
        ["Amount"]
    )

    input_df = input_df[feature_order]

    prediction = model.predict(input_df)[0]

    probability = model.predict_proba(input_df)[0][1]

    st.divider()
    st.header("Prediction Result")

    if prediction == 1:

        st.error(
            "⚠️ Potential Fraudulent Transaction Detected"
        )

        st.metric(
            "Fraud Probability",
            f"{probability * 100:.2f}%"
        )

        st.warning(
            "This prediction is generated by a machine learning "
            "model and should not be treated as a real banking decision."
        )

    else:

        st.success(
            "✅ Transaction Classified as Legitimate"
        )

        st.metric(
            "Fraud Probability",
            f"{probability * 100:.2f}%"
        )

    with st.expander("View Transaction Data"):
        st.dataframe(
            input_df,
            use_container_width=True
        )

st.divider()

st.caption(
    "Credit Card Fraud Detection System | Machine Learning Mini Project"
)
